# Generated by go2rpm 1.10.0
%bcond_without check

# https://github.com/fortio/fortio
%global goipath         fortio.org/fortio
%global forgeurl        https://github.com/fortio/fortio
Version:                1.63.4

%gometa -L -f


%global common_description %{expand:
Fortio load testing library, command line tool, advanced echo server and web UI
in go (golang). Allows to specify a set query-per-second load and record
latency histograms and other useful stats.}

%global golicenses      LICENSE
%global godocs          docs CONTRIBUTING.md README.md SECURITY.md\\\
                        cli_test.txtar .testdata/payloadTest1.txt\\\
                        debian/changelog dflag/README.md release/README.md

Name:           golang-fortio
Release:        %autorelease
Summary:        Fortio load testing library, command line tool, advanced echo server and web UI in go (golang). Allows to specify a set query-per-second load and record latency histograms and other useful stats

License:        Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%build
%gobuild -o %{gobuilddir}/bin/fortio %{goipath}
for cmd in echosrv histogram fcurl; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc docs CONTRIBUTING.md README.md SECURITY.md cli_test.txtar
%doc .testdata/payloadTest1.txt debian/changelog dflag/README.md
%doc release/README.md
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
